name: Build and test

on:
  push:
    branches: [ main ]
    paths:
      - training-app/**
      - training-ft/**
  pull_request:
    branches: [ main ]
    paths:
      - training-app/**
      - training-ft/**
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build app
        run: ./gradlew --no-daemon :training-app:build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run unit tests
        run: ./gradlew --no-daemon :training-app:test
      - name: Run functional tests
        run: ./gradlew --no-daemon :training-ft:cucumber
